-- This script uses H2 Database specific language extensions "IF NOT EXISTS" to make it idempotent

CREATE TABLE IF NOT EXISTS ACCOUNT (ACCOUNTID VARCHAR, NICKNAME VARCHAR, PRIMARY KEY (ACCOUNTID));
CREATE TABLE IF NOT EXISTS NICKNAME (NICKNAME VARCHAR, COUNT INTEGER NOT NULL, PRIMARY KEY (NICKNAME));
